### PR TITLE
Fix #103 

### LINKED ISSUE #103: ActionGroups don't stop scheduling child actions if they get interrupted
Suppose I am running an autonomous routine with the `CommandCreator` and disable it halfway through, calling `Action#interrupted` on the `ActionGroup` that is currently running. When I go to reenable the robot, the `ActionGroup` picks up where it left off. 

To reproduce:

```
    @Test
    public void testKillingActionGroups() throws Exception
    {
        TimeWarpedClock clock = new TimeWarpedClock(10);

        MainActionScheduler actionScheduler = new MainActionScheduler(clock); // don't use TimeWarpedSimulator in order to gain access to futures

        AtomicDouble number1 = new AtomicDouble();
        ActionGroup ag = new ActionGroup()
                .addSequential(() -> number1.getAndAdd(1))
                .addSequential(new TimedPeriodicAction(250, TimeUnit.MILLISECONDS))
                .addSequential(() -> number1.getAndAdd(1))
                .addSequential(new TimedPeriodicAction(1000, TimeUnit.MILLISECONDS))
                .addSequential(() -> number1.getAndAdd(1))
                .addSequential(new TimedPeriodicAction(250, TimeUnit.MILLISECONDS))
                .addSequential(() -> number1.getAndAdd(1));

        Future<Void> voidFuture = actionScheduler.scheduleAction(ag);
        while(true) {
            if(number1.get() == 2) // Kill actiongroup when number is 2
            {
                ag.interrupted();
                voidFuture.cancel(true);
                break;
            }
        }

        Thread.sleep(1000); // Wait for any potential remaining actions to get scheduled/executed
        assertEquals(2, number1.get()); // Should be 2 since we killed it when number1 was 2. Is actually 4.
    }
```

### PR DESCRIPTION
**Pull request by ritikmishra**

### CODE REVIEW

**Comment by ritikmishra** [comment]
I sort of made a mistake and accidentally added the simpson's rule-based localizer to this branch. sorry about that.

**Comment by andrewgazelka** [comment]
I'll accept this as this fixes the issue for now. However, there is a much larger issue with `interrupted()` which I will explain in an issue in about 3 min.

File: Core/src/main/java/com/github/ezauton/core/action/ActionGroup.java [hunk 1]
```diff
@@ -182,10 +183,12 @@ public Action getAction() {
     @Override
     public final void run(ActionRunInfo actionRunInfo) throws ExecutionException {
         List<WithActionData> withActions = new ArrayList<>();
-//        List<Future<Void>> withActionFutures = new ArrayList<>();
         List<Future<Void>> actionFutures = new ArrayList<>();
 
         for (ActionWrapper scheduledAction : scheduledActions) {
+            if(interrupted) { // stop scheduling new actions
+                break;
```
Comment (andrewgazelka) [inline Core/src/main/java/com/github/ezauton/core/action/ActionGroup.java]: This does fix it... however, it will still not cancel the blocked actions right away which imo bad implementation. I think instead of relying on an `interrupted()` method, all `Action`s should just rely on `InterruptedException` like normal Java threads. Actions which normally loop (`PeriodicAction`) could have an additional `interrupted()` method, but this would be part of the `PA` impl, not part of the `Action` interface.

File: Core/src/test/java/com/github/ezauton/core/test/utils/ActionTest.java [hunk 2]
```diff
@@ -291,4 +292,35 @@ public void testUpdateableGroup() {
         assertTrue(list.isEmpty());
     }
 
+
+    @Test
+    public void testKillingActionGroups() throws Exception
+    {
+        TimeWarpedClock clock = new TimeWarpedClock(10);
+
+        MainActionScheduler actionScheduler = new MainActionScheduler(clock);
```
Comment (andrewgazelka) [inline Core/src/test/java/com/github/ezauton/core/test/utils/ActionTest.java]: Good job using an `ActionScheduler`
